# Welcome {.unnumbered}

This is the website for the 2nd edition of **"R for Data Science"**. This book will teach you how to do data science with R: You'll learn how to get your data into R, get it into the most useful structure, transform it and visualize.  
这是 **《R 数据科学》** 第二版的网站。本书将教你如何使用 R 进行数据科学：你将学习如何将数据导入 R、将其整理成最有用的结构，并对其进行转换与可视化。

In this book, you will find a practicum of skills for data science. Just as a chemist learns how to clean test tubes and stock a lab, you'll learn how to clean data and draw plots---and many other things besides. These are the skills that allow data science to happen, and here you will find the best practices for doing each of these things with R. You'll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You'll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualizing, and exploring data.  
在本书中，你将获得一套系统的数据科学实战技能。就像化学家学习如何清洗试管和整理实验室一样，你将学习如何清洗数据、绘制图形，以及更多相关技能。这些技能让数据科学成为可能，而你将在此处学到使用 R 完成这些任务的最佳实践。你将学会使用图形语法（grammar of graphics）、释义式编程（literate programming）以及可重复性研究（reproducible research）来节省时间。你还将学习如何管理认知资源，以便在数据清洗、可视化和探索过程中促进发现。

This website is and will always be free, licensed under the [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) License. If you'd like a physical copy of the book, you can order it on [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20). If you appreciate reading the book for free and would like to give back, please make a donation to [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): the [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (which appears on the cover of R4DS) is a critically endangered parrot native to New Zealand; there are only 244 left.  
本网站现在并且永远向所有人免费开放，内容遵循 [CC BY‑NC‑ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) 许可证。如果你希望拥有纸质版书籍，可以在 [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20) 订购。如果你喜欢免费阅读本书并希望回馈，请向 [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate) 捐款：封面上的 [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) 是新西兰特有的极危鹦鹉，现存仅 244 只。

If you speak another language, you might be interested in the freely available translations of the 1st edition:  
如果你使用其他语言，也许会对第一版的免费翻译感兴趣：

* [Spanish](http://es.r4ds.hadley.nz)
  西班牙语译本：[http://es.r4ds.hadley.nz](http://es.r4ds.hadley.nz)
* [Italian](https://it.r4ds.hadley.nz)
  意大利语译本：[https://it.r4ds.hadley.nz](https://it.r4ds.hadley.nz)
* [Turkish](https://tr.r4ds.hadley.nz)
  土耳其语译本：[https://tr.r4ds.hadley.nz](https://tr.r4ds.hadley.nz)
* [Portuguese](https://pt.r4ds.hadley.nz)
  葡萄牙语译本：[https://pt.r4ds.hadley.nz](https://pt.r4ds.hadley.nz)

You can find suggested answers to exercises in the book at [https://mine-cetinkaya-rundel.github.io/r4ds-solutions](https://mine-cetinkaya-rundel.github.io/r4ds-solutions).  
你可以在 [https://mine-cetinkaya-rundel.github.io/r4ds-solutions](https://mine-cetinkaya-rundel.github.io/r4ds-solutions) 找到本书练习题的参考答案。

Please note that R4DS uses a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html). By contributing to this book, you agree to abide by its terms.  
请注意，R4DS 遵循 [贡献者行为准则](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html)。参与本书贡献即表示你同意遵守其条款。
